# Generated by Django 5.1.2 on 2024-10-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SklepMeblowy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='kod_pocztowy',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='miasto',
        ),
    ]
